# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: elastic:changeme@localhost, port: 9200 }
    indexes:
        blog: # the name of our index
            settings:
                index:
                    analysis:
                        analyzer:
                            keyword_analyzer: # this is a custom analyzer, see the explanations below
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, trim]
            types:
                post: # the name of our type
                    properties:
                        title:
                            analyzer: keyword_analyzer
                            search_analyzer: keyword_analyzer
                            type: text
                    persistence:
                        driver: orm
                        model: App\Entity\Post
                        provider: ~
                        finder: ~
                        repository: App\Repository\SearchRepository\SearchPostRepository